name: 'Compare a npm package version with your package.json'
description: 'Output node version number from package.json engines field'

author: Rober19

inputs:
  path:
    description: 'Path of package.json'
    default: "./" 
  npm_package_name:
    description: 'npm package name to make comparison'   
    required: true
outputs:
  version:
    description: "project version from version field in package.json"
  npm_is_greater:
    description: "npm version comparison with local one"


runs:
  using: 'node12'
  main: 'lib/index.js'


branding:
  icon: 'check-square'
  color: 'green'