name: Build
on:
  push:
    branches:
      - master
      - d2
    # paths:
    #   - "src/**"
    #   - "package.json"
    #   - ".github/workflows/build.yml"

jobs:
  build:
    name: Build compiled JS version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Unit Test
        run: npm test

      - name: Compile TypeScript into compressed JavaScript
        run: npm run build
     
      - name: Local action test
        uses: ./
        id: version
        with: 
          path: "./"
          npm_package_name: sql-csv-insert-processor

      - name: Get version
        run: |
          echo "Version is  ${{ steps.version.outputs.version }} "    
          echo "Version NPM is  ${{ steps.version.outputs.pkg_npm_version }} "    
          echo "npm_is_greater is  ${{ steps.version.outputs.npm_is_greater }} "    
      # ------------------

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v4
      #   with:
      #     add: lib
      #     message: "[auto] build: update compiled version"
      #     force: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
